### ISSUE TITLE
APP支付请求参数是否可以通过此SDK进行组装和签名

### ISSUE THREAD

**Issue by lance-ding** [alipay/alipay-sdk-nodejs#20]
目前app支付请求参数在服务器端组装完后传到app中进行调用，此SDK是否提供这个功能？调用的接口名称为为 `alipay.trade.app.pay`.

**Comment by tudou527** [comment]
这是服务端的 sdk，不建议放到 app 中使用（存在泄露私钥的风险）

**Comment by lance-ding** [comment]
@tudou527 谢谢你的回复。目前是在服务端做的组装签名，app会通过api请求服务器端获取签名数据。 我的意思是，此sdk是否可以做组装签名的工作。
通过源码看这个sdk做了对支付宝发起请求的封装，不需要向支付宝发起请求的操作就不能使用这个sdk了，可以这样理解吗？

**Comment by tudou527** [comment]
简单理解是这样的。

**Comment by lance-ding** [comment]
好的， 谢谢 @tudou527
