### ISSUE TITLE
alipay.trade.app.pay 接口问题

### ISSUE THREAD

**Issue by lingoh** [alipay/alipay-sdk-nodejs#21]
使用最新版本，调用alipay.trade.app.pay就报 [AlipaySdk]HTTP 请求错误， 调用其他接口正常，比方付款到支付宝

**Comment by tudou527** [comment]
请提供 demo

**Comment by lingoh** [comment]
是我的问题，alipay.trade.app.pay只要签名后丢给客户端，不是服务端请求网关，官方文档api有点误导的感觉，node希望能提供个单独的签名方法调用

**Comment by leekafai** [comment]
> 是我的问题，alipay.trade.app.pay只要签名后丢给客户端，不是服务端请求网关，官方文档api有点误导的感觉，node希望能提供个单独的签名方法调用

你好，我请求这个接口的时候返回404，这是什么情况？

**Comment by ItVen** [comment]
我也是这情况  [AlipaySdk]HTTP 请求错误 问了技术支持 感觉都是答非所问

**Comment by tudou527** [comment]
PC 支付接口文档：https://www.yuque.com/chenqiu/alipay-node-sdk/page_api#SyhyY

**Comment by lqh940916** [comment]
> 是我的问题，alipay.trade.app.pay只要签名后丢给客户端，不是服务端请求网关，官方文档api有点误导的感觉，node希望能提供个单独的签名方法调用
兄弟你是怎么解决的这个问题

**Comment by tudou527** [comment]
小程序或者 App 的支付接口，只需要实例化后通过 util.sign 方法签名，然后把签名的字符串给客户端就行

**Comment by luoage** [comment]
真坑爹，写完微信支付，再来写的支付宝支付，被误导的概率就更大了

**Comment by victorykong** [comment]
> 小程序或者 App 的支付接口，只需要实例化后通过 util.sign 方法签名，然后把签名的字符串给客户端就行

那你们文档能调整下吗？没有看到相关说明啊

**Comment by lazyfish88** [comment]
> 小程序或者 App 的支付接口，只需要实例化后通过 util.sign 方法签名，然后把签名的字符串给客户端就行

你们就不能把说明完善下吗？几行代码的事，能帮开发人员少走很多歪路

**Comment by seekcx** [comment]
写的什么玩意儿

**Comment by troyeagle** [comment]
> @tudou527 写的什么玩意儿

3.3.0 以后的版本已经修复了这个问题，如有疑问请反馈，感谢。
