### ISSUE TITLE
支持哪些api？

### ISSUE THREAD

**Issue by zaoqishibing** [alipay/alipay-sdk-nodejs#22]
如题，预授权api支持吗？可以构造唤起支付宝客户端支付的请求吗？

**Comment by popomore** [comment]
接口是 https://docs.open.alipay.com/api

这个是服务端调用的接口，唤起的话可能是前端接口。

**Comment by tudou527** [comment]
@zaoqishibing  开放平台上提供的 api 都能支持。但目前没有换起支付宝客户端的 api。
