### ISSUE TITLE
invalid-signature

### ISSUE THREAD

**Issue by Maples7** [alipay/alipay-sdk-nodejs#25]
```typescript
    this.alipaySdk = new AlipaySdk({
      appId: alipayConfig.appId,
      gateway: alipayConfig.gateway,
      privateKey: fs
        .readFileSync(path.join(__dirname, './app-private-key.pem'), 'ascii')
        .trim(),
      alipayPublicKey: fs
        .readFileSync(path.join(__dirname, './alipay-public-key.pem'), 'ascii')
        .trim(),
      charset: 'utf-8',
      signType: 'RSA2',
    });
```

```typescript
    const formData = new AlipayFormData();
    formData.setMethod('get');
    formData.addField(
      'notifyUrl',
      new URL(
        path.join(this.configService.apiPrefix, 'transactions/alipay/notify'),
        this.configService.website,
      ).toString(),
    );
    formData.addField(
      'returnUrl',
      new URL('/alipay/result', this.configService.website).toString(),
    );
    formData.addField('bizContent', {
      outTradeNo: tradeNo,
      productCode: 'FAST_INSTANT_TRADE_PAY',
      totalAmount: totalFee,
      subject: this.subject,
      body: this.description,
    });

    try {
      const result = await this.alipaySdk.exec(
        'alipay.trade.page.pay',
        {},
        {
          formData,
          validateSign: true,
          log: console,
        },
      );
      if (_.isString(result)) {
        return result;
      } else {
        throw new Error(
          `[main] [${result.code}] ${result.msg} - [sub] [${result.sub_code} ${
            result.sub_msg
          }]`,
        );
      }
    } catch (err) {
      this.logger.error('Fail to create direct payment url of alipay', err);
      throw new ApiException(ERRORS.PROXY_ERROR, '创建阿里云支付链接失败');
    }
```

沙箱环境下：

生成的付款地址调用一直返回：

> 错误代码 invalid-signature 错误原因: 验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：alipay_sdk=alipay-sdk-nodejs-3.0.4&amp;app_id=2016092500596274&amp;biz_content={&quot;out_trade_no&quot;:&quot;201900123Test&quot;,&quot;product_code&quot;:&quot;FAST_INSTANT_TRADE_PAY&quot;,&quot;total_amount&quot;:&quot;0.01&quot;,&quot;subject&quot;:&quot;心知天气服务费&quot;,&quot;body&quot;:&quot;心知天气为你提供准确、稳定、全面的天气数据服务。&quot;}&amp;charset=utf-8&amp;method=alipay.trade.page.pay&amp;notify_url=http://hansel-dev.seniverse.com/api/v1/transactions/alipay/notify&amp;return_url=http://hansel-dev.seniverse.com/alipay/result&amp;sign_type=RSA2&amp;timestamp=2019-03-11 13:12:03&amp;version=1.0

生成的调用地址：

> https://openapi.alipaydev.com/gateway.do?method=alipay.trade.page.pay&app_id=2016092500596274&charset=utf-8&version=1.0&sign_type=RSA2&timestamp=2019-03-11%2013:12:03&notify_url=http://hansel-dev.seniverse.com/api/v1/transactions/alipay/notify&return_url=http://hansel-dev.seniverse.com/alipay/result&sign=psu3WygBOcDgkt95tTXfV7yo1oIOB6c9mgnXKqKioTbh77wkaZhSBRTeZBLCJU6V6bwyP8Hxh7V0Jblx8Wg8FYNlb29FIFVQ30edccHbrblBN0kVFa4QBDdhwKFLOoYxmKSVYK5J/hz5CfiMrkxD1T5uM1NFit0eX/5ZelX8hjr3xDmjy3JsyZvrn+TTLHIp3khI5ZMKSAmcWEclx81MJGGQajsE+zV8b1FZHDvWtKVOmCnBNUJE7QMLJUoGLqIWqasFsyLY02/URsQUV5pAH+Sx1oNNMdpPp7gfSpCQANBcKqNSJ/HX3+LlRXtovOp8w8DOeD2nETtPUpKdn5o0YQ==&alipay_sdk=alipay-sdk-nodejs-3.0.4&biz_content=%7B%22out_trade_no%22:%22201900123Test%22,%22product_code%22:%22FAST_INSTANT_TRADE_PAY%22,%22total_amount%22:%220.01%22,%22subject%22:%22%E5%BF%83%E7%9F%A5%E5%A4%A9%E6%B0%94%E6%9C%8D%E5%8A%A1%E8%B4%B9%22,%22body%22:%22%E5%BF%83%E7%9F%A5%E5%A4%A9%E6%B0%94%E4%B8%BA%E4%BD%A0%E6%8F%90%E4%BE%9B%E5%87%86%E7%A1%AE%E3%80%81%E7%A8%B3%E5%AE%9A%E3%80%81%E5%85%A8%E9%9D%A2%E7%9A%84%E5%A4%A9%E6%B0%94%E6%95%B0%E6%8D%AE%E6%9C%8D%E5%8A%A1%E3%80%82%22%7D

但是用验签工具确定公钥私钥是匹配的，Help! 🤕

**Comment by Maples7** [comment]
正式环境测试结果也一样，生成的地址：

> https://openapi.alipay.com/gateway.do?method=alipay.trade.page.pay&app_id=2019030863516283&charset=utf-8&version=1.0&sign_type=RSA2&timestamp=2019-03-11%2014:21:36&notify_url=https://www.seniverse.com/api/v1/transactions/alipay/notify&return_url=https://www.seniverse.com/alipay/result&sign=Sg2fv7pND/9iswwo8uJo4wdHl5SzdffrlEieiSA40zpdymO7a40uVrQKw6cve8PO/L/3oPBy6llYYfQdHFCOuHe+8blZouKog1tJSGJI2AxYxN0kdyFTEVph3sAuNhjufm397l73ijT1HKsTR9QuWNQacgJHCX9bSNrjn51tnc0deOvUKqi0FREDPToUzTKbYmMHi9qGPM2WjbO6spQSZeY7zilL3ob+KsPzCnFUnkQcD09/vDclxXxeYxgmTPaQ+4YK7nLgsX/MyfATwwW+6LVv+shYplysqZ+StUM8MPNKb1SNXrNqev6joAJR51Z3ZT+4snRQuPYHSjAOeyUTlQ==&alipay_sdk=alipay-sdk-nodejs-3.0.4&biz_content=%7B%22out_trade_no%22:%22201900123Test%22,%22product_code%22:%22FAST_INSTANT_TRADE_PAY%22,%22total_amount%22:%220.01%22,%22subject%22:%22%E5%BF%83%E7%9F%A5%E5%A4%A9%E6%B0%94%E6%9C%8D%E5%8A%A1%E8%B4%B9%22,%22body%22:%22%E5%BF%83%E7%9F%A5%E5%A4%A9%E6%B0%94%E4%B8%BA%E4%BD%A0%E6%8F%90%E4%BE%9B%E5%87%86%E7%A1%AE%E3%80%81%E7%A8%B3%E5%AE%9A%E3%80%81%E5%85%A8%E9%9D%A2%E7%9A%84%E5%A4%A9%E6%B0%94%E6%95%B0%E6%8D%AE%E6%9C%8D%E5%8A%A1%E3%80%82%22%7D

**Comment by Maples7** [comment]
Fixed：Chrome 自动转义，生成的 URL 是没问题的。

**Comment by Maples7** [comment]
证实跟 VSCode 的行为有关：https://github.com/Microsoft/vscode/issues/70197

**Comment by fatetop** [comment]
验签出错后 怎么验签成功的 help 同样的问题
