### ISSUE TITLE
沙盒通知校验签名失败 

### ISSUE THREAD

**Issue by zcong1993** [alipay/alipay-sdk-nodejs#27]
sdk `checkNotifySign` 校验沙盒通知失败, 需要去掉 `sign_type`

**Comment by tudou527** [comment]
开放平台的现状：不同的接口不太一样，有些需要去掉 sign_type，有些不需要（略坑，正在推动改进）。

目前的 SDK 默认不会去掉 sign_type 需要自己手动处理
