### ISSUE TITLE
sdk 支持 商家代扣签约时signStr拼接吗？

### ISSUE THREAD

**Issue by SunYuanOnly** [alipay/alipay-sdk-nodejs#28]
怎样用sdk实现？

**Comment by tudou527** [comment]
sdk 中已经包含计算签名相关的逻辑了

**Comment by SunYuanOnly** [comment]
sdk怎么生成签名？

**Comment by SunYuanOnly** [comment]
` alipaySdk.pageExec('https://openapi.alipay.com/gateway.do', {
            method: 'alipay.user.agreement.page.sign',
            notifyUrl: 'https://webox.vveye.com/wx/d',
            returnUrl: 'https://webox.vveye.com/wx/d',
            bizContent: {
                external_agreement_no: 'test',
                personal_product_code: 'ONE_TIME_AUTH_P',
                sign_scene: 'INDUSTRY|VENDING_MACHINE'
            }
        }, {})
            .then(result => {
               // console.log(result);
               return onSuccess(result);
            })
            .catch(error => {
                console.log(error);
                return onError(error);
            })`
这样调用的时候提示errorMessage: '[AlipaySdk]HTTP 请求错误' }

**Comment by SunYuanOnly** [comment]
![image](https://user-images.githubusercontent.com/16498201/57688219-85d09e80-766f-11e9-8101-07808e2e5d6b.png)
 sdk 能实现这个吗？

**Comment by tudou527** [comment]
demo：https://www.yuque.com/chenqiu/alipay-node-sdk/with_biz_content
