### ISSUE TITLE
@types/urllib is a stub types definition

### ISSUE THREAD

**Issue by cncolder** [alipay/alipay-sdk-nodejs#29]
https://unpkg.com/urllib@2.34.0/package.json

**Comment by atian25** [comment]
urllib 已经自带 d.ts 了，这个仓库可以不用引入 @types/urllib@

**Comment by tudou527** [comment]
https://github.com/alipay/alipay-sdk-nodejs/commit/178b4e8803c0ed9f3a6ca35fa55caae60b060e55#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L19
