### ISSUE TITLE
Ionic APP 开发，实现支付宝APP支付，需要后端支付宝SDK返回一个签名alipayOrder...

### ISSUE THREAD

**Issue by qqaimh** [alipay/alipay-sdk-nodejs#35]
Ionic APP 开发，实现支付宝APP支付，需要后端支付宝SDK返回一个签名alipayOrder，
"alipayOrder is a string that has been generated and signed by the server side."
然后在app里使用这个alipayOrder去唤醒移动端支付宝，完成支付
我想询问一下，这个alipayOrder是否由alipay-sdk/lib/util.js 里的sigin( )函数产生？

**Comment by tudou527** [comment]
可以这么生成

**Comment by qqaimh** [comment]
> 可以这么生成
谢谢，我在确定一下，根据这个函数的签名
/**
 * 签名
 * @param {string} method 调用接口方法名，比如 alipay.ebpp.bill.add
 * @param {object} bizContent 业务请求参数
 * @param {object} publicArgs 公共请求参数
 * @param {object} config sdk 配置
 */
function sign(method, params = {}, config) {}
除了method 调用接口方法名、onfig sdk 配置，是直传入bizContent 业务请求参数，publicArgs 公共请求参数就可以了吗？

**Comment by tudou527** [comment]
是，建议直接试试
