### ISSUE TITLE
显示INVALID_PARAMETER

### ISSUE THREAD

**Issue by yilikunNEO** [alipay/alipay-sdk-nodejs#37]
按照demo写的,但是一直显示`INVALID_PARAMETER`
![image](https://user-images.githubusercontent.com/43943437/60755673-69c0fc00-a025-11e9-9333-d5fc068326fe.png)
求助

**Comment by yilikunNEO** [comment]
确定参数无误

**Comment by yilikunNEO** [comment]
`import AlipayFormData from 'alipay-sdk/lib/form';

const formData = new AlipayFormData();
// 调用 setMethod 并传入 get，会返回可以跳转到支付页面的 url
formData.setMethod('get');

formData.addField('notifyUrl', 'http://www.com/notify');
formData.addField('bizContent', {
  outTradeNo: 'out_trade_no',
  productCode: 'FAST_INSTANT_TRADE_PAY',
  totalAmount: '0.01',
  subject: '商品',
  body: '商品详情',
});

const result = await alipaySdk.exec(
  'alipay.trade.page.pay',
  {},
  { formData: formData },
);

// result 为可以跳转到支付链接的 url
console.log(result);
`

**Comment by tudou527** [comment]
用例中有能正常调用的测试代码，可以参考：https://github.com/alipay/alipay-sdk-nodejs/blob/master/test/alipay.test.js#L660-L675
