### ISSUE TITLE
怎么解密my.getPhoneNumber的加密内容？

### ISSUE THREAD

**Issue by ChangedenCZD** [alipay/alipay-sdk-nodejs#51]
`{"response":"voCTGYUDyMV+oI6beut6cxnniJyhPGJA3o79HjSz/0ui/3nLpFZ07AkKl0NK4xs18HoiTlC3V9CvWh43Sdza7MNn2qZ4p9YvrsgHWK
1rKm9qEsFmP9mcyO347osrsrjKc9C4R9XBMe89Pe4llz9l8XKr0szCFhkXKANfD1j8eQVRNbpKiatotmpbUc5PWwlyX1ArVZ7FYZ3C6igH2Yp7hzzjjjml5qixQ+Rtx7jtxWRik3WSUzh8ToWKuKupQ7/IGupFxdWZCsXicr+RFqFUqBHzmVVhImHqsGMKyUBT18O04KmjAy4btepqxMhu7+x6jrBV9DbJ2oQ4D3ncu2OoR9gWY5U7otcXpsp
i4G1PkBk=","sign":"iWck70SU2/LhzN76YP1qkY8H5fdpRzVVZqsLDI+YpBX2i5pSPcUqos64YDgzdUUQvTYPzcT4j+SrGCcl+bk1emwG8r7cmhOUKByeYhFWsSVMT6roQTCqAdI+z9UWTAg/rLyZIyxKYBxbxjXJ7m4q4eyNZ+MXoVx5nwA3hhFx6SRnYMCyXvhEt6ny1/PSuhkuPvXOFtUkIFQiE3Y0JVji
2tzHgrJO/M+lhsLl5/+3MZzNaIPQ/FB+rrx581O1TKQxN7PZ7KOq3I01fyDtb1YfIUWG56hqBzJBW9Ryc460JdpjrwBGdKTX2luoIks4E7CemPi9tFsjOGz4AEfEk9qQpA=="}`

**Comment by tudou527** [comment]
请看官方的文档，SDK 暂时没有提供这个能力。
