### ISSUE TITLE
电脑网页支付通过alipay.trade.page.pay， 传fromdata, get方法获得一个url, 然后浏览器访问url，是这个样子吗？

### ISSUE THREAD

**Issue by jiayiming001** [alipay/alipay-sdk-nodejs#52]
![image](https://user-images.githubusercontent.com/32919372/68646483-40295b80-0556-11ea-9580-6e44d7cfa4e5.png)
然后出现了这个问题。

私钥和支付宝公钥已经替换3次保障不会错，下面是diao'yong调用代码， result 是拿到的url
![image](https://user-images.githubusercontent.com/32919372/68646536-6d760980-0556-11ea-9e9e-7ac98fc3b57d.png)

**Comment by tudou527** [comment]
参考这个 Demo：https://www.yuque.com/chenqiu/alipay-node-sdk/page_api#SyhyY

**Comment by jiayiming001** [comment]
我尝试了这个Demo， 访问获得的url，得到了验签出错

**Comment by jiayiming001** [comment]
@tudou527 我发你了邮件，里面有更加详细的信息，帮我看一下问题，感谢

**Comment by jiayiming001** [comment]
原因找到了，这个sdk是不支持证书的，只有java语言的sdk支持支付宝公匙证书，所有换成支付宝公匙就好了
